[versions]
kotest = "6.2.3"
coroutines = "1.11.0"
logging = "8.0.4"
logback = "1.6.3"
arrow = "2.2.3"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience-jvm", version.ref = "arrow" }
arrow-fx-stm = { module = "io.arrow-kt:arrow-fx-stm-jvm", version.ref = "arrow" }
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

kotest-core = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
