[versions]
kotest = "6.2.3"
coroutines = "1.10.2"
logging = "8.0.4"
logback = "1.6.3"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

kotest-core = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
