ktor {
  deployment {
    port = 9090
  }
  application {
    modules = [
      pro.artkart.config.ModulesKt.myModule
    ]
  }
  //    database {
  //        url = ${DB_URL}
  //        driver = ${DB_DRIVER}
  //        user = ${DB_USER}
  //        password = ${DB_PASSWORD}
  //    }
}
