ktor {
    deployment {
        port = 9090
    }
    application {
        modules = [
            pro.artkart.config.ModulesKt.configureNegotiation,
            pro.artkart.config.DatabaseKt.configureDatabase,
            pro.artkart.config.RoutingKt.configureRouting
        ]
    }
    database {
        url = ${DB_URL}
        driver = ${DB_DRIVER}
        user = ${DB_USER}
        password = ${DB_PASSWORD}
    }
}
